# Source: jxboot-helmfile-resources/templates/buildpacks.yaml
apiVersion: jenkins.io/v1
kind: BuildPack
metadata:
  name: "classic-workloads"
  namespace: jx
spec:
  label: "Library Workloads: CI+Release but no CD"
  gitUrl: "https://github.com/jenkins-x-buildpacks/jenkins-x-classic.git"
  gitRef: "master"
---
# Source: jxboot-helmfile-resources/templates/buildpacks.yaml
apiVersion: jenkins.io/v1
kind: BuildPack
metadata:
  name: "kubernetes-workloads"
spec:
  label: "Kubernetes Workloads: Automated CI+CD with GitOps Promotion"
  gitUrl: "https://github.com/jenkins-x-labs/jenkins-x-kubernetes.git"
  gitRef: "master"
