---
# Source: wave/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    {}
  labels:
    app: wave
    release: "pusher"
    chart: "wave-1.0.0"
    heritage: "Helm"
  name: pusher-wave
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave
      release: "pusher"
      chart: "wave-1.0.0"
      heritage: "Helm"
  template:
    metadata:
      labels:
        app: wave
        release: "pusher"
        chart: "wave-1.0.0"
        heritage: "Helm"
    spec:
      containers:
        - image: "quay.io/pusher/wave:v0.4.0"
          imagePullPolicy: IfNotPresent
          name: pusher-wave
          args:
      securityContext: 
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: pusher-wave
      nodeSelector: 
        {}
