apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: jx-pipeline-git-github-github
  namespace: jx
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: github
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  vaultMountPoint: kubernetes
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  vaultRole: vault-infra
  data:
  - name: username
    key: secret/data/jx/pipelineUser
    property: username
  - name: password
    key: secret/data/jx/pipelineUser
    property: token
