apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: lighthouse-oauth-token
  namespace: jx
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.633"
    release: "lighthouse"
    heritage: "Helm"
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  vaultMountPoint: kubernetes
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  vaultRole: vault-infra
  data:
  - name: oauth
    key: secret/data/jx/pipelineUser
    property: token
