apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: tekton-git-token
  namespace: jx
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  vaultMountPoint: kubernetes
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  vaultRole: vault-infra
  data:
  - name: username
    key: secret/data/jx/pipelineUser
    property: username
  - name: password
    key: secret/data/jx/pipelineUser
    property: token
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
    type: kubernetes.io/basic-auth
