---
# Source: jx/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jx
  namespace: jx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx
subjects:
- kind: ServiceAccount
  name: jx
  namespace: jx
