apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodey460-nodey460
  template:
    metadata:
      labels:
        app: nodey460-nodey460
        draft: draft-app
    spec:
      containers:
      - env: null
        envFrom: null
        image: gcr.io/jstrachan-multicluster/nodey460:1.0.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nodey460
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
      terminationGracePeriodSeconds: null
